include "Utility/MRenderGlobal.fbs";

namespace morty.fbs;

table MSlice
{
    offset: uint;
    num: uint;
}

table MClusterBounds
{
    position: Vector3;
    radius: float;
    error: float;
}

table MCluster
{
    group: int;
    refined: int;
    indices_offset: uint;
    indices_num: uint;
    bounds: MClusterBounds;
}

table MClusterPage
{
    vertex: [byte];
    index: [uint];
}

table MClusterGroup
{
    cluster_offset: uint;
    cluster_num: uint;
    bounds: MClusterBounds;
    parent_group_id: int = -1;
    first_child_group_id: int = -1;
    child_group_count: uint = 0;
}

file_identifier "MFBS";