include "Math/Vector.fbs";
include "Math/Quaternion.fbs";
include "Math/Matrix.fbs";
include "Utility/MBoundsOBB.fbs";
include "Utility/MBoundsSphere.fbs";
include "Model/MSkeleton.fbs";
include "Utility/MRenderGlobal.fbs";
include "Mesh/MCluster.fbs";

namespace morty.fbs;

enum MEMeshVertexType:byte
{
    normal = 0,
    skeleton = 1,
}

table MMeshResource
{
	bounds_obb: MBoundsOBB;
    bounds_sphere: MBoundsSphere;

    vertex_type: MEMeshVertexType;

    vertex: [byte];
    index: [uint];

    cluster: [MCluster];
    group: [MClusterGroup];
    lod: [MSlice];
}

root_type MMeshResource;

file_identifier "MFBS";