# User-defined console commands.
commands:
  - name: test_import
    description: "Import a test model"
    commands:
      - "convert ../../../../Resource/Model/banana/ripe-banana.obj ../../../Resource/nanite --nanite"
  - name: test_load
    description: "Create a test scene and open editor"
    commands:
      - "scene create test"
      - "load ../../../Resource/nanite/ripe-banana/ripe-banana.entity test"
      - "set test ripe-banana.obj/ripe-banana/ripe-banana:MSceneComponent:Position 0,0,50"
